version: '3.8'

services:
  elb:
    image: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
      - ./ssl://etc/ssl/private

  main-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${MAIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_NAME}
    expose:
      - "${MAIN_DB_PORT}"
    ports:
      - "${MAIN_DB_PORT}:${MAIN_DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: -p ${MAIN_DB_PORT}
    volumes:
      - main-data:/var/lib/postgresql/data

  authorization-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${AUTHORIZATION_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTHORIZATION_DB_PASSWORD}
      POSTGRES_DB: ${AUTHORIZATION_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - "${AUTHORIZATION_DB_PORT}"
    ports:
      - "${AUTHORIZATION_DB_PORT}:${AUTHORIZATION_DB_PORT}"
    command: -p ${AUTHORIZATION_DB_PORT}
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"

  main-service:
    build: ./MainService
    environment:
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
      RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      DB_USERNAME: ${MAIN_DB_USERNAME}
      DB_PASSWORD: ${MAIN_DB_PASSWORD}
      DB_PORT: ${MAIN_DB_PORT}
      DB_HOSTNAME: main-db
      DB_NAME: ${MAIN_DB_NAME}
      APP_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - main-db
      - rabbitmq

  notification-service:
    build: ./NotificationService
    environment:
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
      RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
    depends_on:
      - rabbitmq

  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://authorization-db:${AUTHORIZATION_DB_PORT}/${AUTHORIZATION_DB_NAME}
      KC_DB_USERNAME: ${AUTHORIZATION_DB_USERNAME}
      KC_DB_PASSWORD: ${AUTHORIZATION_DB_PASSWORD}

      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_PROXY: "https://localhost/"
      KC_PROXY_TRUSTED_ADDRESSES: "https://localhost/"
      KC_SERVICE_FQDN: keycloak
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_URL: "http://localhost:8083/oauth/"
      KC_HOSTNAME_ADMIN_URL: "https://localhost:8084/oauth/"

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"

      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}


    command: start-dev --http-port=8083 --https-port=8084 --http-relative-path=\oauth --https-certificate-file=/etc/ssl/private/test.pem --https-certificate-key-file=/etc/ssl/private/test.key --hostname-strict-backchannel=true
    depends_on:
      - authorization-db
    volumes:
      - ./ssl:/etc/ssl/private
    ports:
      - "8083:8083"
      - "8084:8084"

volumes:
  main-data:
  auth-db-data:
